/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 fall_guys_crown.glb --transform 
Files: fall_guys_crown.glb [38.98KB] > C:\Users\kirkl\Desktop\202406\fall_guys_crown-transformed.glb [6.6KB] (83%)
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fall-guys-crown-64e55ffd4f864a20a943710c581d194f
Title: Fall Guys Crown
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fall_guys_crown-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={[1.347, 1, 1.347]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.003']} scale={[1.347, 1, 1.347]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} scale={[1.347, 1, 1.347]} />
    </group>
  )
}

useGLTF.preload('/fall_guys_crown-transformed.glb')
