/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 oolong2.glb --transform 
Files: oolong2.glb [769.1KB] > C:\Users\kirkl\Desktop\202405\oolong2-transformed.glb [179.22KB] (77%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
// import { useGame } from "ecctrl";

export function Oolong(props) {
  const circleRef = useRef();
  const date = useRef(0);
  // const setMoveToPoint = useGame((state) => state.setMoveToPoint);
  const { nodes, materials } = useGLTF("models/oolong2-transformed.glb");
  return (
    <>
      <mesh ref={circleRef} rotation-x={-Math.PI / 2}>
        <ringGeometry args={[0.2, 0.3]} />
        <meshBasicMaterial color={0x000000} transparent opacity={0.25} />
      </mesh>

      <RigidBody type="fixed" colliders="trimesh" ccd>
        <group position={[0, 0, 0]} scale={6} {...props} dispose={null}>
          <mesh
            geometry={nodes.pCube56_q00103.geometry}
            material={materials.lambert1_v}
            position={[-4.286, 2.871, 0.009]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.165}
          />
          <mesh
            geometry={nodes.pCylinder29_q00106.geometry}
            material={materials.tou_01_2_lambert67_v_x}
            position={[-4.329, 1.716, 0.011]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.165}
          />
          <mesh
            geometry={nodes.pPlane216_q00107_part0.geometry}
            material={materials.tou_01_2_lambert58_v}
            position={[-3.925, 2.605, 0.009]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.076}
          />
          <mesh
            geometry={nodes.pPlane216_q00107_part1.geometry}
            material={materials.tou_01_2_lambert61_v}
            position={[-3.925, 2.605, 0.009]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.076}
          />
          <mesh
            geometry={nodes.pCylinder35_q00120.geometry}
            material={materials.EX_lambert2_v}
            position={[-3.3, -0.138, -1.1]}
            rotation={[Math.PI / 2, 0, 1.969]}
            scale={[0.138, 0.138, 0.11]}
          />
          <mesh
            geometry={nodes.polySurface382_q00121.geometry}
            material={materials.lambert85_v}
            position={[-3.3, 2.062, -0.756]}
            rotation={[Math.PI / 2, 0.133, -Math.PI]}
            scale={0.138}
          />
          <mesh
            geometry={nodes.door_2.geometry}
            material={materials.lambert12_v}
            position={[-2.205, -0.003, 1.504]}
            rotation={[Math.PI / 2, 0, Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCube86_q00128.geometry}
            material={materials.lambert13_v}
            position={[-2.115, 1.248, 0.899]}
            rotation={[Math.PI / 2, 0, -Math.PI / 3]}
            scale={[0.076, 0.076, 0.082]}
          />
          <mesh
            geometry={nodes.polySurface292_q00137_part1.geometry}
            material={materials.lambert66_v}
            position={[2.585, -0.151, 3.65]}
            rotation={[Math.PI / 2, 0, Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface301_q00138.geometry}
            material={materials.lambert80_v}
            position={[2.585, -0.085, 3.65]}
            rotation={[Math.PI / 2, 0, Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface302_q00139.geometry}
            material={materials.lambert64_v}
            position={[2.585, -0.085, 3.65]}
            rotation={[Math.PI / 2, 0, Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCylinder12_q00140_part0.geometry}
            material={materials.tou_01_lambert4_v}
            position={[-1.765, 1.36, 0.297]}
            rotation={[1.606, 0.075, 0.611]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCylinder12_q00140_part1.geometry}
            material={materials.tou_01_lambert7_v}
            position={[-1.765, 1.36, 0.297]}
            rotation={[1.606, 0.075, 0.611]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface1302_q00144.geometry}
            material={materials.lambert124_v}
            position={[3.15, -0.085, 1.505]}
            rotation={[Math.PI / 2, 0, Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface1304_q00152.geometry}
            material={materials.lambert126_v}
            position={[-0.571, 0, 3.378]}
            rotation={[Math.PI / 2, 0, -Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface252_q00153_part0.geometry}
            material={materials.lambert68_v}
            position={[-2.475, 0, 1.515]}
            rotation={[Math.PI / 2, 0, -0.175]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface252_q00153_part1.geometry}
            material={materials.lambert74_v}
            position={[-2.475, 0, 1.515]}
            rotation={[Math.PI / 2, 0, -0.175]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface252_q00153_part2.geometry}
            material={materials.tou_01_lambert9_v}
            position={[-2.475, 0, 1.515]}
            rotation={[Math.PI / 2, 0, -0.175]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.sak_tes_1.geometry}
            material={materials.lambert82}
            position={[-2.746, -0.083, 3.659]}
            rotation={[Math.PI / 2, 0, -Math.PI / 6]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCylinder32_q00156_part2.geometry}
            material={materials.tou_01_kadan_lambert4_v}
            position={[1.975, 1.305, 1.584]}
            rotation={[-3.136, 1.047, -1.575]}
            scale={[0.076, 0.083, 0.083]}
          />
          <mesh
            geometry={nodes.door_1_a_part0.geometry}
            material={materials.lambert57_v}
            position={[0, 0.33, -3.026]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCylinder10_q00168_part0.geometry}
            material={materials.lambert84_v}
            position={[2.269, 0.901, -2.067]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface375_q00174_part2.geometry}
            material={materials.lambert81_v}
            position={[0, -0.083, 1.375]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface67_q00176_part1.geometry}
            material={materials.lambert52_v}
            position={[0, 0.082, 0.962]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.polySurface67_q00176_part2.geometry}
            material={materials.lambert70_v}
            position={[0, 0.082, 0.962]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCube84_q00184.geometry}
            material={materials.lambert78_v}
            position={[0, 1.67, -0.847]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pCube85_q00185.geometry}
            material={materials.lambert77_v}
            position={[0, 1.679, -0.839]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.pSphere7_q00186.geometry}
            material={materials.lambert76}
            position={[0, 2.721, -0.935]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.083, 0.083, 0.079]}
          />
          <mesh
            geometry={nodes.pCube104_q00187_part0.geometry}
            material={materials.lambert87}
            position={[4.016, 0.66, -2.326]}
            rotation={[Math.PI / 2, 0, -2.356]}
            scale={0.055}
          />
          <mesh
            geometry={nodes.pCube42_q00200_part0.geometry}
            material={materials.tou_01_2_lambert11_v}
            position={[4.696, 0.055, 2.484]}
            rotation={[Math.PI / 2, 0, -0.093]}
            scale={0.055}
          />
          <mesh
            geometry={nodes.polySurface277_q00208_part1.geometry}
            material={materials.tou_01_2_lambert56_v}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.055}
          />
          <mesh
            geometry={nodes.polySurface1305_q00210_part0.geometry}
            material={materials.tou_01_2_lambert10_v}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.275}
          />
          <mesh
            geometry={nodes.polySurface1313_q00213.geometry}
            material={materials.yuu_lambert125_v}
            position={[0, -1.65, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.44, 0.44, 0.55]}
          />
          <mesh
            geometry={nodes.sati_1.geometry}
            material={materials.tou_01_2_lambert75_v_x}
            position={[-3.053, 0.385, -6.419]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.083}
          />
          <mesh
            geometry={nodes.tougi.geometry}
            material={materials.tou_01_2_lambert79_v}
            position={[0, 0.632, -5.61]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.084, 0.083, 0.117]}
          />
          <instancedMesh
            args={[
              nodes.meshpolySurface1306_q00147.geometry,
              materials.lambert80_v,
              5,
            ]}
            instanceMatrix={nodes.meshpolySurface1306_q00147.instanceMatrix}
          />
          <instancedMesh
            args={[nodes.meshjet_1.geometry, materials.lambert7_v_x, 8]}
            instanceMatrix={nodes.meshjet_1.instanceMatrix}
          />
        </group>
      </RigidBody>
    </>
  );
}

useGLTF.preload("models/oolong2-transformed.glb");
