/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 qb.glb --transform 
Files: qb.glb [137.41KB] > C:\Users\kirkl\Desktop\202406\qb-transformed.glb [18.46KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function QuestionBlock(props) {
  const { nodes, materials } = useGLTF('models/qb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.BlockQuestion__BlockQuestionMat00020.geometry} material={materials.BlockQuestionMat00} position={[70.562, 9.136, 0]} />
      <mesh castShadow geometry={nodes.BlockQuestion__BlockQuestionMat01020.geometry} material={materials.BlockQuestionMat01} position={[70.562, 9.136, 0]} />
    </group>
  )
}

useGLTF.preload('models/qb-transformed.glb')
