/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 stylized_tent.glb --transform 
Files: stylized_tent.glb [2.18MB] > C:\Users\kirkl\Downloads\stylized_tent-transformed.glb [228.23KB] (90%)
Author: csabat3D (https://sketchfab.com/taczi.csaba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tent-e5a32b9c07a941f78411bd1145f85fdf
Title: Stylized Tent
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tent(props) {
  const { nodes, materials } = useGLTF('models/stylized_tent-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tent_Mat_0.geometry} material={materials.material} position={[-5.82, -40.821, 54.371]} />
    </group>
  )
}

useGLTF.preload('models/stylized_tent-transformed.glb')
